version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  vue-server:
    image: registry.cn-hangzhou.aliyuncs.com/zzkun/short-url-vue

  spring-server:
    image: registry.cn-hangzhou.aliyuncs.com/zzkun/short-url-web
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    links:
      - db

  server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - vue-server
      - spring-server
    links:
      - vue-server
      - spring-server
